# Generated by Django 5.0.4 on 2024-05-04 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='review',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 1, 26, 4, 595748)),
        ),
    ]
